---

# tasks file for nginx

- name: Copiar o repositorio oficial do ngnix para o servidor
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root
  when: ansible_hostname == 'srv03'

- name: Instalacao dos pacotes nginx
  yum:
    name: ['nginx.x86_64','nginx-module-geoip.x86_64']
    state: latest
  when: ansible_hostname == 'srv03' 

- name: Criar copia de seguranca do /etc/nginx
  command: mv /etc/nginx /etc/nginx_original
  args:
    warn: false
  when: ansible_hostname == 'srv03'

- name: Copiar o nginx.tar.gz para o servidor
  unarchive:
    src: nginx.tar.gz
    dest: /etc/
    owner: root
    group: root
  when: ansible_hostname == 'srv03'

- name: Criacao de diretorios do nginx
  file: path={{item}} state=directory mode=0755 owner=nginx group=nginx
  with_items:
    - /var/www
    - /var/www/html
  notify: Restart nginx
  when: ansible_hostname == 'srv03'

...