---

- hosts: all
  remote_user: root
  vars:
    - new_password: 123456

  tasks:

  - name: INSTALL REQUIREMENT Expect - Executes a command and responds to prompts
    yum:
      name: pexpect
      state: latest

  - name: TESTING Update Root User's Password
    expect:
      command: passwd root
      responses:
        (?i)password: "{{ new_password }}"
    #user:
      #name: root
      #state: present
      #update_password: always
      #password: "{{ new_password }}"
