---

- hosts: all
  remote_user: root
  
  vars_prompt:
  - name: root_pwd
    prompt: "Enter Password: "
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7
    
  tasks:
  - name: Change Password
    user:
      name: root
      password: "{{ root_pwd | password_hash('sha512') }}"
      update_password: always

  ### ATTEMPT 02 - FAIL

  # - name: INSTALL REQUIREMENT Expect - Executes a command and responds to prompts
  #   yum:
  #     name: pexpect
  #     state: latest

  # - name: TESTING Update Root User's Password
  #   expect:
  #     command: passwd root
  #     responses:
  #       (?i)password: "{{ new_password }}"
    
  ### ATTEMPT 01 - FAIL
    
  # user:
  #   name: root
  #   state: present
  #   update_password: always
  #   password: "{{ new_password }}"
