---

- hosts: all
  remote_user: root

  tasks:

  - name: TESTING Update Root User's Password
    user:
      name: root
      state: present
      update_password: always
      password: "{{ abc123zyx }}"
