---

- hosts: all
  remote_user: root
  vars:
    - new_password: abc123zyx

  tasks:

  - name: TESTING Update Root User's Password
    user:
      name: root
      state: present
      update_password: always
      password: "{{ new_password }}"
